name: math_compute
version: 0.0.1
description: A library to lex, parse and compute mathematical expressions.

repository: 'https://github.com/theskyblockman/math_compute'
issue_tracker: 'https://github.com/theskyblockman/math_compute/issues'

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  logging: ^1.2.0
  rational: ^2.2.3

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
